### ISSUE TITLE
bug: assertion failed: tv_nsec >= 0 && tv_nsec < NSEC_PER_SEC as i64 in time.rs

### ISSUE THREAD

**Issue by tleepa** [eza-community/eza#666]
I am getting an error while listing my `~/.cache` directory with gradient color scale for age:
```
thread 'main' panicked at 'assertion failed: tv_nsec >= 0 && tv_nsec < NSEC_PER_SEC as i64', library/std/src/sys/unix/time.rs:77:9
```

I do not know why this particular error happens in this exact directory. My `~/.cache` (149 entries):
```
.rw-r--r--@  17M leepa 2023-11-16 11:41:56.094477964 +0100 plasma_theme_Dracula_v1.0.0.kcache
.r--r--r--@ 367k leepa 2023-11-16 11:35:39.056682278 +0100 p10k-dump-leepa.zsh.zwc
.rw-------@ 163k leepa 2023-11-16 11:35:39.049682244 +0100 p10k-dump-leepa.zsh
(...)
drwxr-xr-x@    - leepa 2021-11-26 11:23:00.801486231 +0100 akonadi_ical_resource_0
drwxr-xr-x@    - leepa 2021-11-26 11:22:55.787765675 +0100 abrt
drwxrwxr-x@    - leepa 2021-11-26 11:22:54.859817395 +0100 ksplashqml
```

Info
---
- The version of eza being used
```
❯ eza --version
eza - A modern, maintained replacement for ls
v0.15.3 [+git]
https://github.com/eza-community/eza
```
- The command-line arguments you are using
```
❯ eza -l --color-scale age .cache
```
- Your operating system and hardware platform
```
❯ inxi -S --no-host
System:
  Kernel: 6.5.11-300.fc39.x86_64 arch: x86_64 bits: 64 Desktop: KDE Plasma
    v: 5.27.9 Distro: Fedora release 39 (Thirty Nine)
```
- Backtrace:
```
❯ RUST_BACKTRACE=full eza -l --color-scale age .cache
thread 'main' panicked at 'assertion failed: tv_nsec >= 0 && tv_nsec < NSEC_PER_SEC as i64', library/std/src/sys/unix/time.rs:77:9
stack backtrace:
   0:     0x561710ec489c - <unknown>
   1:     0x561710e738ff - <unknown>
   2:     0x561710e9db94 - <unknown>
   3:     0x561710ec5f0f - <unknown>
   4:     0x561710ec5b0e - <unknown>
   5:     0x561710ec6b80 - <unknown>
   6:     0x561710ec6634 - <unknown>
   7:     0x561710ec65c6 - <unknown>
   8:     0x561710ec65b1 - <unknown>
   9:     0x561710e17ba2 - <unknown>
  10:     0x561710e17c9c - <unknown>
  11:     0x561710e3567e - <unknown>
  12:     0x561710e40b5c - <unknown>
  13:     0x561710e420d7 - <unknown>
  14:     0x561710e637bd - <unknown>
  15:     0x561710e6212c - <unknown>
  16:     0x561710e6157a - <unknown>
  17:     0x561710e5f01c - <unknown>
  18:     0x561710e1ea23 - <unknown>
  19:     0x561710e66d2d - <unknown>
  20:     0x7f4c6d26d14a - __libc_start_call_main
  21:     0x7f4c6d26d20b - __libc_start_main_impl
  22:     0x561710e1e009 - <unknown>
  23:                0x0 - <unknown>
```

---

**Comment by tleepa** [comment]
Debug:
```
❯ RUST_BACKTRACE=full ./Downloads/eza -l --color-scale age .cache 
thread 'main' panicked at library/std/src/sys/unix/time.rs:77:9:
assertion failed: tv_nsec >= 0 && tv_nsec < NSEC_PER_SEC as i64
stack backtrace:
   0:     0x558bcafb413c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb3291a57fade45e0
   1:     0x558bcafdb02c - core::fmt::write::hfdd5aaf5eb3de157
   2:     0x558bcafb128d - std::io::Write::write_fmt::ha5af58e43aa46d70
   3:     0x558bcafb3f24 - std::sys_common::backtrace::print::h0b08a90a15e49bcf
   4:     0x558bcafb55d3 - std::panicking::default_hook::{{closure}}::h7dc2bac5c0aaae86
   5:     0x558bcafb52ec - std::panicking::default_hook::h0560519392c08460
   6:     0x558bcafb5b59 - std::panicking::rust_panic_with_hook::h4774589ac7e41b5c
   7:     0x558bcafb5a11 - std::panicking::begin_panic_handler::{{closure}}::h1106262a85badff0
   8:     0x558bcafb4666 - std::sys_common::backtrace::__rust_end_short_backtrace::h1fec32bba27becfa
   9:     0x558bcafb57a2 - rust_begin_unwind
  10:     0x558bcad5db03 - core::panicking::panic_fmt::hede3e62893827817
  11:     0x558bcad5db93 - core::panicking::panic::h14f37d955e916819
  12:     0x558bcafaece8 - std::fs::Metadata::created::h984233f3f5c9ac99
  13:     0x558bcada6fb3 - eza::fs::file::File::created_time::h97ec3e3e1cd105d2
                               at /home/leepa/Repos/Public/eza/src/fs/file.rs:750:9
  14:     0x558bcad85960 - eza::output::color_scale::update_information_recursively::h19c440059ffbb706
                               at /home/leepa/Repos/Public/eza/src/output/color_scale.rs:116:17
  15:     0x558bcad85551 - eza::output::color_scale::ColorScaleInformation::from_color_scale::hf584a8548ba88cdf
                               at /home/leepa/Repos/Public/eza/src/output/color_scale.rs:57:13
  16:     0x558bcadca6a4 - eza::output::details::Render::render::ha544ee4ecc97b7e2
                               at /home/leepa/Repos/Public/eza/src/output/details.rs:168:32
  17:     0x558bcad94a4f - eza::Exa::print_files::hdc8c6c57f67dd48c
                               at /home/leepa/Repos/Public/eza/src/main.rs:420:17
  18:     0x558bcad9398c - eza::Exa::print_dirs::h02643105116164db
                               at /home/leepa/Repos/Public/eza/src/main.rs:357:13
  19:     0x558bcad92581 - eza::Exa::run::hc96fc848c75cb5dc
                               at /home/leepa/Repos/Public/eza/src/main.rs:274:9
  20:     0x558bcad90ef2 - eza::main::h89869d841fb220d2
                               at /home/leepa/Repos/Public/eza/src/main.rs:89:19
  21:     0x558bcadd6ffb - core::ops::function::FnOnce::call_once::hf56bfc70306ef65f
                               at /builddir/build/BUILD/rustc-1.73.0-src/library/core/src/ops/function.rs:250:5
  22:     0x558bcadb2a0e - std::sys_common::backtrace::__rust_begin_short_backtrace::h1cc4bd966d0add1e
                               at /builddir/build/BUILD/rustc-1.73.0-src/library/std/src/sys_common/backtrace.rs:154:18
  23:     0x558bcad61b21 - std::rt::lang_start::{{closure}}::hcfed4e7c54272ebb
                               at /builddir/build/BUILD/rustc-1.73.0-src/library/std/src/rt.rs:166:18
  24:     0x558bcaface2b - std::rt::lang_start_internal::h70f1b381b1939be6
  25:     0x558bcad61afa - std::rt::lang_start::he7e25a3147277438
                               at /builddir/build/BUILD/rustc-1.73.0-src/library/std/src/rt.rs:165:17
  26:     0x558bcad94eee - main
  27:     0x7fd3d7ff314a - __libc_start_call_main
  28:     0x7fd3d7ff320b - __libc_start_main_impl
  29:     0x558bcad5e2b5 - _start
  30:                0x0 - <unknown>
```

**Comment by daviessm** [comment]
@tleepa Sorry, forgot to say, the "created time" is the `btime` field (birth time), you can get it in `ls` with `ls -l --time=birth`

**Comment by tleepa** [comment]
Found the culprit:
```
❯ /usr/bin/ls -ltr --time=birth .cache
(...)
drwxr-xr-x. 1 leepa leepa       16 5047840295228529719  ksmserver-logout-greeter
```

**Comment by daviessm** [comment]
That would do it! Can you delete or recreate that file? `eza` shouldn't panic so I'll look at handling the error though.

**Comment by tleepa** [comment]
Yup, re-created all the problematic directories.
Thanks again for your help! :)

**Comment by daviessm** [comment]
I can't actually fix this as the error manifests in the stdlib which explicitly panics if the `btime` is too far out of range. Not much we can do here.

**Comment by daviessm** [comment]
> This is probably [rust-lang/rust#108277](https://github.com/rust-lang/rust/issues/108277) then right?

Yup, looks like it.
